apiVersion: skaffold/v1alpha4
kind: ''
build:
  artifacts:
    - image: shanelee007/graphql
deploy:
  kubectl:
    manifests:
      - kubernetes/config.yaml
      - kubernetes/deployment.yaml
      - kubernetes/secret.yaml
