apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: shanelee007/graphql
deploy:
  kubectl:
    manifests:
    - kubernetes/config.yaml
    - kubernetes/deployment.yaml
    - kubernetes/secret.yaml
